### ISSUE TITLE
template parse error when importing the MultiselectDropdownModule in app.module

### ISSUE THREAD

**Issue by sharathgg5** [softsimon/angular-2-dropdown-multiselect#147]
i get the following error in console. when i import MultiselectDropdownModule  in app.module.
but i haven't used the <ss-multiselect-dropdown> any where in the template yet. but initial import itself has errors. i don't know what's error or may be i need to upadate my package.json...

Error:
`Unhandled Promise rejection: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("!option.isLabel && setSelected($event, option)" [class.dropdown-header]="option.isLabel">
          [ERROR ->]<ng-template [ngIf]="option.isLabel">
            {{ option.name }}
          </ng-template>
"): MultiselectDropdown@36:10 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError Error: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("!option.isLabel && setSelected($event, option)" [class.dropdown-header]="option.isLabel">
          [ERROR ->]<ng-template [ngIf]="option.isLabel">
            {{ option.name }}
          </ng-template>
"): MultiselectDropdown@36:10
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:1137:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:98672:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:11263:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:25588:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:61816:68)
    at http://localhost:4200/vendor.bundle.js:61699:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:61699:19)
    at createResult (http://localhost:4200/vendor.bundle.js:61581:19)
    at ZoneDelegate.webpackJsonp.1341.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:479:26)
    at Zone.webpackJsonp.1341.Zone.run (http://localhost:4200/polyfills.bundle.js:271:43)
    at http://localhost:4200/polyfills.bundle.js:858:57
    at ZoneDelegate.webpackJsonp.1341.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:512:31)
    at Zone.webpackJsonp.1341.Zone.runTask (http://localhost:4200/polyfills.bundle.js:311:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:691:35)`
My package.json:
`{
  "name": "S3.web.Desktop",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.10",
    "@angular/compiler": "^2.4.10",
    "@angular/core": "^2.4.10",
    "@angular/forms": "^2.4.10",
    "@angular/http": "^2.4.10",
    "@angular/platform-browser": "^2.4.10",
    "@angular/platform-browser-dynamic": "^2.4.10",
    "@angular/router": "^3.4.10",
    "core-js": "^2.4.1",
    "moment": "^2.18.1",
    "ng2-bootstrap": "^1.6.3",
    "rxjs": "^5.2.0",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-rc.1",
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.42",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~2.5.0",
    "karma": "~1.2.0",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~4.0.13",
    "ts-node": "~1.2.1",
    "tslint": "~4.3.0",
    "typescript": "~2.2.1",
    "postcss-loader": "1.3.3",
    "minimatch": "3.0.2"
  }
}
`

**Comment by chris--jones** [comment]
This component now requires angular 4, see #117
