### ISSUE TITLE
[Help Wanted] Importing angular-2-dropdown-multiselect http://localhost:3000/angular-2-dropdown-multiselect 404 (Not Found)

### ISSUE THREAD

**Issue by Malligarjunan** [softsimon/angular-2-dropdown-multiselect#216]
Followed the steps mentioned in README.  But still get the 404 Exception
(index):42 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/angular-2-dropdown-multiselect
	Error: XHR error (404 Not Found) loading http://localhost:3000/angular-2-dropdown-multiselect
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1056:39)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:191:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:486:38)
	Error loading http://localhost:3000/angular-2-dropdown-multiselect as "angular-2-dropdown-multiselect" from http://localhost:3000/app/app.module.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1056:39)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:191:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:486:38)
	Error loading http://localhost:3000/angular-2-dropdown-multiselect as "angular-2-dropdown-multiselect" from http://localhost:3000/app/app.module.js

**Comment by nicholasguyett** [comment]
If you're using SystemJS, you need to update your `systemjs.config,js` to map the `angular-2-dropdown-multiselect` package to the package in your `node_modules` folder.
