### ISSUE TITLE
Dropdown menu is not closing on IE

### ISSUE THREAD

**Issue by naveenballa** [softsimon/angular-2-dropdown-multiselect#57]
Dropdown menu is not closed on IE after clicking outside.
Even the demo link is not working on IE (http://softsimon.github.io/angular-2-dropdown-multiselect/)
Observed some error as below
```
Error: Object doesn't support property or method 'keys'
Error loading http://softsimon.github.io/angular-2-dropdown-multiselect/src/main.ts
   {
      [functions]: ,
      __proto__: { },
      description: "undefined",
      message: "Object doesn't support property or method 'keys'
	Error loading http://softsimon.github.io/angular-2-dropdown-multiselect/src/main.ts",
      name: "Error",
      number: NaN,
      stack: "TypeError: Object doesn't support property or method 'keys'
   at Anonymous function (https://code.angularjs.org/2.0.0-beta.15/angular2.dev.js:842:5)
   at Anonymous function (https://code.angularjs.org/2.0.0-beta.15/angular2.dev.js:841:3)
   at i (https://code.angularjs.org/tools/system.js:4:31560)
   at s (https://code.angularjs.org/tools/system.js:4:31192)
   at Anonymous function (https://code.angularjs.org/tools/system.js:4:31647)
   at Anonymous function (https://code.angularjs.org/2.0.0-beta.15/angular2.dev.js:11361:3)
   at i (https://code.angularjs.org/tools/system.js:4:31560)
   at s (https://code.angularjs.org/tools/system.js:4:31192)
   at Anonymous function (https://code.angularjs.org/tools/system.js:4:31647)
   at Anonymous function (https://code.angularjs.org/2.0.0-beta.15/angular2.dev.js:12594:3)"
   }
```

**Comment by nicholasguyett** [comment]
Which version of IE?

**Comment by nicholasguyett** [comment]
IE doesn't support the keys property.  You'll need to to include a polyfill for Object.keys in your project.  Angular 2 recommends the core-js package which will provide all the necessary polyfills.
